2021-04-02 GUARD-1814 ChannelAdvisor Error-On-FullInventorySync
skuvault-integrations/channelAdvisorAccess pull request #28
Opened 2021-04-02 08:27 UTC by maxim-saltanov-skuvault

This client is getting an error on the full inventory sync that says "Unexpected character encountered while parsing value: <. Path '', line 0, position 0."

This occurs when if the title / description / sku etc.. of the product contains a quotation mark before the angle bracket or something like that

![11234](https://user-images.githubusercontent.com/80940351/113397651-0ef93780-93a6-11eb-8be2-a70e33d4673b.png)

We discussed with team and agreed to add logz for problematic http response, then release and investigate again.

2021-04-02 11:33 UTC, nathan-skuvault approved these changes

2021-04-05 15:23 UTC, maxim-skuvault commented on src/ChannelAdvisorAccess/REST/Services/ServiceBaseAbstr.cs
> +							catch ( Exception err )
We normally name an Exception variable `ex`

2021-04-05 15:28 UTC, maxim-skuvault commented on src/ChannelAdvisorAccess/REST/Services/ServiceBaseAbstr.cs
> +								ChannelAdvisorLogger.LogTrace( String.Format( "Failed due to: '{0}', response: {1}", err.Message, content ) );
@maxim-saltanov-skuvault Is the BA Ok with just logging the error but not re-throwing? After this change we'll absorb the error and then process subsequent batches. To the client it will look like the sync ran normally. There will only be an integration log to indicate that a batch failed. This is probably Ok, but is worth verifying.

2021-04-05 15:29 UTC, maxim-skuvault reviewed
@maxim-saltanov-skuvault See inline comments. Also, there should be package version update.

2021-04-06 13:03 UTC, maxim-saltanov-skuvault commented on src/ChannelAdvisorAccess/REST/Services/ServiceBaseAbstr.cs
> +								ChannelAdvisorLogger.LogTrace( String.Format( "Failed due to: '{0}', response: {1}", err.Message, content ) );
@maxim-skuvault you're right, we need to re-throwing the error. I will fix it.

2021-04-06 14:57 UTC, maxim-skuvault requested changes
@maxim-saltanov-skuvault There are two other open PRs here:
1. https://github.com/skuvault/channelAdvisorAccess/pull/27 : This has been released, based on the RLS-1914 status (Completed) and the comments in that RLS (tested in prod). It can be merged into master (@jnewman-sv said he'll do it). Once merged, you should pull from master into the 1814 branch, and change this PR accordingly
2. https://github.com/skuvault/channelAdvisorAccess/pull/23 : This has NOT been released, so you don't have to do anything about this PR. We moved it to the backlog early Fall, so it's on Hold and the PR is badly outdated

I'll post a Slack comment about our process

2021-04-07 16:44 UTC, jnewman-sv approved these changes

2021-04-07 19:32 UTC, maxim-skuvault commented on src/Global/GlobalAssemblyInfo.cs
> +[ assembly : AssemblyVersion( "8.9.2.0" ) ]
@maxim-saltanov-skuvault , This is still the old version. Master is at 8.10.2. Need to pull from master and then increment the version

2021-04-08 08:46 UTC, maxim-saltanov-skuvault commented
> @maxim-saltanov-skuvault There are two other open PRs here:
> 
> 1. #27 : This has been released, based on the RLS-1914 status (Completed) and the comments in that RLS (tested in prod). It can be merged into master (@jnewman-sv said he'll do it). Once merged, you should pull from master into the 1814 branch, and change this PR accordingly
> 2. #23 : This has NOT been released, so you don't have to do anything about this PR. We moved it to the backlog early Fall, so it's on Hold and the PR is badly outdated
> 
> I'll post a Slack comment about our process

Done, I pulled from the master branch and resolved conflicts.

2021-04-08 18:43 UTC, maxim-skuvault commented on src/ChannelAdvisorAccess/REST/Services/ServiceBaseAbstr.cs
> +									throw new ChannelAdvisorException( (int) HttpStatusCode.InternalServerError, error );
@maxim-saltanov-skuvault , Are you sure this needs to throw since in Prod we're just setting `batchStatusCode = (int)httpResponse.StatusCode;` in this "else" and then advancing to the next batch? We could still add logging but I didn't think we wanted to change how the app functions at this time.

2021-04-09 06:19 UTC, maxim-saltanov-skuvault commented on src/ChannelAdvisorAccess/REST/Services/ServiceBaseAbstr.cs
> +									throw new ChannelAdvisorException( (int) HttpStatusCode.InternalServerError, error );
@maxim-skuvault I think that if we get a response that we cannot parse, then we should throw an error. If we do not do this, then as you said earlier, we will simply skip some of the products and synchronize the rest and the inventorysync integration will be displayed as successful - I think this is wrong. Probably we will need to discuss it with BA...

2021-04-19 15:38 UTC, maxim-skuvault commented on src/ChannelAdvisorAccess/REST/Services/ServiceBaseAbstr.cs
> -						throw channelAdvisorException;
@maxim-saltanov-skuvault I am confused. You removed rethrowing. So now this "catch" will swallow the exception and it will not trigger a retry or failed sync, as it currently does in Prod. I thought we were trying to avoid changing the sync behavior, but just add logging. Am I misunderstanding something? Same in other places here.

2021-04-19 15:51 UTC, maxim-skuvault requested changes

2021-04-19 15:51 UTC, maxim-skuvault commented on src/ChannelAdvisorAccess/REST/Services/ServiceBaseAbstr.cs
> +						ChannelAdvisorLogger.LogTrace( String.Format( "Failed due to: '{0}', response: {1}", responseEx.Message, responseStr ) );
@maxim-saltanov-skuvault I just noticed that the log entries you added in this file don't log the "mark". Which means that when this is logged we'll have no way of tracing it back to a specific sync run instance or even a tenant/SV account. 

There might be some identifying information in the error itself (Channel Advisor id or Url?) but it would be better to also log the mark. You can look at examples like this:
`var channelAdvisorException = new ChannelAdvisorException( this.CreateMethodCallInfo( mark : mark, additionalInfo : this.AdditionalLogInfo() ), exception );
ChannelAdvisorLogger.LogTraceException( channelAdvisorException );`
You can also pass the `responseStr` as the `methodResult` parameter into `CreateMethodCallInfo`. And even `returnStatusCode` if that would be helpful for future troubleshooting. I see `httpResponse.StatusCode` in some places here. 

In the example above, I don't see a way to customize the logged text, which might be helpful for the parsing log below. You might have to do something different for that, but definitely log the mark everywhere

2021-04-19 16:48 UTC, maxim-saltanov-skuvault commented on src/ChannelAdvisorAccess/REST/Services/ServiceBaseAbstr.cs
> -						throw channelAdvisorException;
@maxim-skuvault you're right, should be fixed for now

2021-04-19 16:49 UTC, maxim-saltanov-skuvault commented on src/ChannelAdvisorAccess/REST/Services/ServiceBaseAbstr.cs
> +						ChannelAdvisorLogger.LogTrace( String.Format( "Failed due to: '{0}', response: {1}", responseEx.Message, responseStr ) );
@maxim-skuvault thanks Max, it should be fixed for now

2021-04-19 17:07 UTC, jnewman-sv approved these changes

2021-04-19 17:29 UTC, maxim-skuvault commented on src/ChannelAdvisorAccess/REST/Services/ServiceBaseAbstr.cs
> +								ChannelAdvisorLogger.LogTrace( this.CreateMethodCallInfo( mark : mark, methodParameters: url, methodResult: content, errors: "Failed due to: " + ex.Message, additionalInfo : this.AdditionalLo
@maxim-saltanov-skuvault Why are we not rethrowing after logging here, to preserve the current sync logic?

2021-04-20 05:21 UTC, maxim-saltanov-skuvault commented on src/ChannelAdvisorAccess/REST/Services/ServiceBaseAbstr.cs
> +								ChannelAdvisorLogger.LogTrace( this.CreateMethodCallInfo( mark : mark, methodParameters: url, methodResult: content, errors: "Failed due to: " + ex.Message, additionalInfo : this.AdditionalLo
@maxim-skuvault I don't re-throw at sync in a case of parsing error because we agreed at QA&Core meeting that we shouldn't interrupt the sync in a case of error, so we just write a log and continue sync. 

>[maxim-skuvault] If we don't fail it then the customer won't even know that something hasn't synced. They don't have access to Kibana or integration logs.

yes, I also warned about this at the discussion, but we agreed that this is normal (although, ideally, we ourselves should analyze the logs)

2021-04-20 12:49 UTC, maxim-skuvault approved these changes

2021-04-20 12:49 UTC, maxim-skuvault commented on src/ChannelAdvisorAccess/REST/Services/ServiceBaseAbstr.cs
> +								ChannelAdvisorLogger.LogTrace( this.CreateMethodCallInfo( mark : mark, methodParameters: url, methodResult: content, errors: "Failed due to: " + ex.Message, additionalInfo : this.AdditionalLo
@maxim-saltanov-skuvault Ok

2021-05-26 17:40 UTC, nathan-skuvault approved these changes

2021-07-21 13:19 UTC, merged