2022-01-12 GUARD-2312 ChannelAdvisor session mark and cancellation token refactoring
skuvault-integrations/channelAdvisorAccess pull request #35
Opened 2022-01-12 07:56 UTC by maxim-saltanov-skuvault

**fixes / improvements**
- changed order of the method parameters - I've set CancellationToken as latest parameter across methods as Nathan suggested. Also I've made it optional as it is not required for SOAP (never used) but it uses for REST. 
- made SessionMark as mandatory parameter across methods
- added some missed logz and errors handling across some methods

**commits**: https://github.com/skuvault-integrations/channelAdvisorAccess/commit/98d3e86f630046c236c07a7670332a73c25f2fed and https://github.com/skuvault-integrations/channelAdvisorAccess/commit/801911a8246af59d94c05f40a5a4befad94e8cb5 

**PS**. This branch also contains the changes from other channel advisor tickets https://agileharbor.atlassian.net/browse/GUARD-2225, https://agileharbor.atlassian.net/browse/GUARD-2226 and https://agileharbor.atlassian.net/browse/GUARD-2307

2022-01-13 18:17 UTC, maxim-skuvault commented on src/ChannelAdvisorAccess/REST/Services/Orders/OrdersService.cs
> +		public async Task< IEnumerable< T > > GetOrdersAsync < T >( string filter, Mark mark, int? operationTimeout = null, CancellationToken token = default )
@maxim-saltanov-skuvault , Is this branch building with release.cmd? I wonder if `default` is a recent language feature that won't compile with the [version of MSBuild we're using](https://github.com/skuvault-integrations/channelAdvisorAccess/blob/master/.build.ps1#L25)

2022-01-13 18:37 UTC, maxim-skuvault commented
@maxim-saltanov-skuvault , See inline comment and also a comment on this ticket in JIRA

2022-01-14 13:09 UTC, maxim-saltanov-skuvault commented on src/ChannelAdvisorAccess/REST/Services/Orders/OrdersService.cs
> +		public async Task< IEnumerable< T > > GetOrdersAsync < T >( string filter, Mark mark, int? operationTimeout = null, CancellationToken token = default )
@maxim-skuvault thanks Max, you're right. I've fixed it and it successfully compile now

2022-01-17 13:53 UTC, maxim-skuvault approved these changes

2022-01-21 13:44 UTC, nathan-skuvault approved these changes
so many marks!

2022-02-02 15:28 UTC, maxim-skuvault requested changes
@maxim-saltanov-skuvault , The cancellation token and mark  changes look good. However, just like the earlier PR (2307, I think) this shows RedAlert's changes (Netco, Polly, etc.) even though those changes are already in master - [example](https://github.com/skuvault-integrations/channelAdvisorAccess/blob/master/src/ChannelAdvisorAccess/ChannelAdvisorAccess.csproj#L138). Please try retargeting the PR to another branch and then back to master, to get the diffs to only show your changes.

2022-02-07 17:40 UTC, nathan-newman65190 requested changes
Mark stuff looks good, but it looks like a lot of files are being changed that have nothing to do with the mark refactor.

2022-02-07 17:40 UTC, nathan-newman65190 commented on src/ChannelAdvisorAccess/Service References/AdminService/ChannelAdvisorAccess.AdminService.PingResponse.datasource
> +   <TypeInfo>ChannelAdvisorAccess.AdminService.PingResponse, Service References.AdminService.Reference.cs.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null</TypeInfo>
What are these changes for?

2022-02-07 17:40 UTC, nathan-newman65190 commented on src/ChannelAdvisorAccess/Service References/FulfillmentService/Reference.cs
> +    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
Why the update to these?

2022-02-07 17:40 UTC, nathan-newman65190 commented on src/ChannelAdvisorAccess/Services/Items/ServiceBaseAbstr.cs
> -
Is this not needed for anything?

2022-02-07 17:40 UTC, nathan-newman65190 commented on src/ChannelAdvisorAccess/app.config
> +		<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8" />
Was this intentional?

2022-02-28 08:04 UTC, maxim-saltanov-skuvault commented
> @maxim-saltanov-skuvault , The cancellation token and mark changes look good. However, just like the earlier PR (2307, I think) this shows RedAlert's changes (Netco, Polly, etc.) even though those changes are already in master - [example](https://github.com/skuvault-integrations/channelAdvisorAccess/blob/master/src/ChannelAdvisorAccess/ChannelAdvisorAccess.csproj#L138). Please try retargeting the PR to another branch and then back to master, to get the diffs to only show your changes.

> Please try retargeting the PR to another branch and then back to master, to get the diffs to only show your changes.

Thanks @maxim-skuvault , it helped, I've fixed, and it seems all below's comments outdated now

2022-02-28 15:39 UTC, chris-skuvault approved these changes

2022-02-28 18:27 UTC, maxim-skuvault approved these changes
@maxim-saltanov-skuvault , This looks good presuming that the methods that got moved (UpdateOrderListAsync, GetOrdersAsync) didn't have any changes besides CancellationToken & mark

2022-03-04 16:25 UTC, merged