VT-5739 ChannelAdvisor Product Sync Not Syncing Certain Products
skuvault-integrations/channelAdvisorAccess pull request #43
Opened 2022-12-02 11:22 UTC by mrassudishkin

# Description

Tickets: [VT-5739]

Added new implementation for requests in products sync. We will able to get all products/skus in one request to access project. Also fully ignore any condition for build url. We can just take url for next request to CA from previously response. Tested in Access project with client's data.

## Type of change (should only be one)

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Functionality change (fix or feature that would cause existing functionality to work differently than before)
- [ ] Configuration change
- [ ] New / updated script
- [ ] Refactoring
- [ ] New tests to existing code

# PR Readiness Checklist

Complete all the checklist steps to the best of your ability, marking steps as you complete them or adding comment on why you didn't do it.

- [X] Followed [development conventions][1] to the best of my ability
- [X] Code is documented, particularly public interfaces and hard-to-understand areas
- [X] Tests are updated / added and all pass
- [X] Performed a self-review of my own code
- [X] Acceptance criterias are confirmed by testing changes in UI (or another appropriate way)
- [X] Confluence documentation is updated, if needed
- [X] New code does not generate new warnings
- [X] Formatted new code, according to the applicable rules

[1]: https://agileharbor.atlassian.net/wiki/spaces/DEV/pages/1114130/Conventions

2022-12-02 19:08 UTC, slav requested changes

2022-12-02 19:08 UTC, slav commented on src/ChannelAdvisorAccess/REST/Services/Items/ItemsPagingService.cs
> +		private async Task< List< Product > > GetProducts( string url, Mark mark, int? operationTimeout = null, CancellationToken token = default )
Why not do IEnumerable and yield to return data as we're getting? Then on the client side we can process in batches too. They way it's done right now it might consume a lot of resources (mem) if there's a lot of products, as well as take a while before anything begins to be updated.

2022-12-02 19:08 UTC, slav commented on src/ChannelAdvisorAccess/REST/Services/Items/ItemsPagingService.cs
> +			while( !string.IsNullOrEmpty( nextLink ) )
Formatting? Should be curly braces around try?

2022-12-02 19:08 UTC, slav commented on src/ChannelAdvisorAccess/REST/Services/Items/ItemsPagingService.cs
> +			while( !string.IsNullOrEmpty( nextLink ) )
Also, maybe move try out and do while loop inside try?

2022-12-05 06:23 UTC, mrassudishkin commented on src/ChannelAdvisorAccess/REST/Services/Items/ItemsPagingService.cs
> +		private async Task< List< Product > > GetProducts( string url, Mark mark, int? operationTimeout = null, CancellationToken token = default )
Do you want that I use IAsyncEnumerable ? Then I should use C# version 8.0. Currently we use 7.3
And still one problem: I want overload methods GetFilteredItemsAsync/GetFilteredSkusAsync which we already have in exist ItemsService. I.e I will should rewrite and old methods, but I don't want do it.

2022-12-05 06:26 UTC, mrassudishkin commented on src/ChannelAdvisorAccess/REST/Services/Items/ItemsPagingService.cs
> +		private async Task< List< Product > > GetProducts( string url, Mark mark, int? operationTimeout = null, CancellationToken token = default )
Or I can don't use await/async for this.GetEntityAsync. Then yes - I can use usually IEnumerable and yield.

2022-12-05 06:34 UTC, mrassudishkin commented on src/ChannelAdvisorAccess/REST/Services/Items/ItemsPagingService.cs
> +			while( !string.IsNullOrEmpty( nextLink ) )
I can't use yield inside try.

2022-12-05 12:12 UTC, slav commented on src/ChannelAdvisorAccess/REST/Services/Items/ItemsPagingService.cs
> +			while( !string.IsNullOrEmpty( nextLink ) )
So why not keep yield outside of try? You're not returning from inside try in your current code either

2022-12-07 14:19 UTC, dk-skuvault approved these changes
Approved with small notes

2022-12-07 14:19 UTC, dk-skuvault commented on src/ChannelAdvisorAccess/REST/Services/Items/ItemsPagingService.cs
> +			return ( from product in result select product.ToInventoryItemResponse() ).ToList();
Should we convert it to List if we return IEnumerable?

2022-12-07 14:19 UTC, dk-skuvault commented on src/ChannelAdvisorAccess/REST/Services/Items/ItemsPagingService.cs
> +			return ( from product in result select product.ToInventoryItemResponse() ).ToList();
Also why not use short Linq syntax?

2022-12-08 03:48 UTC, slav commented on src/ChannelAdvisorAccess/REST/Services/Items/ItemsPagingService.cs
> +			return ( from product in result select product.ToInventoryItemResponse() ).ToList();
on public interface it's best to use IEnumerable. It's more generic interface. If in the future we decide to return the data dynamically (using yield), we won't risk breaking the client. I'd say we should return IEnumerable unless we have really good reason not to. And if we need to return collection, we could return IReadOnlyCollection

2022-12-08 06:14 UTC, mrassudishkin commented on src/ChannelAdvisorAccess/REST/Services/Items/ItemsPagingService.cs
> +			return ( from product in result select product.ToInventoryItemResponse() ).ToList();
@dk-skuvault Done
@slav Did IEnumerable. IReadOnlyCollection is more newer version C# language

2022-12-08 09:40 UTC, dk-skuvault approved these changes

2022-12-09 02:58 UTC, slav approved these changes

2022-12-09 06:34 UTC, merged